services:
  actual_server:
    container_name: actual_budget
    image: ghcr.io/actualbudget/actual:latest
    volumes:
      - ./data:/data
    env_file:
      - ../../.env
    restart: unless-stopped
    networks:
      - frontend_net
    # ports:
    #  - "5006:5006"

networks:
  frontend_net:
    external: true
